### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by ghent360** [BETZtechnik/ICEpick--Direct-drive-pick-and-place-head#1]
Please provide a BOM. Pretty please with cherry on top.

**Comment by CWrecker** [comment]
Yes please do

**Comment by CWrecker** [comment]
Is this thread dead?

**Comment by BETZtechnik** [comment]
Not sure if I noticed this thread. I will have to get on a computer and check it out. I’m hearing that you guys want a machine BOM. That’s probably easy enough for me to whip up. 


Peter Betz
Betz Technik Industries Ltd. 
BETZtechnik.ca

**Comment by CWrecker** [comment]
Super. Thanks.

**Comment by BETZtechnik** [comment]
Hello everyone,

I have started a BOM on the product page for the PnP head. I posted the link on the BOM tab here!

Peter.
