### ISSUE TITLE
The new version of the cad file cannot be opened! Can you handle it?

### ISSUE THREAD

**Issue by chenpeng198877** [BETZtechnik/ICEpick--Direct-drive-pick-and-place-head#2]
http://a360.co/2gCUnZz

**Comment by BETZtechnik** [comment]
I confirmed the issue, then saved the model as new version, then it doesn't error in A360, but the model still doesn't show in the window. It seems you can download the fusion archive though at least. Let me know if this works. I may pass this along to the Fusion team.....

I will also take this opportunity to add the new head here.

**Comment by chenpeng198877** [comment]
thank you very much

**Comment by BETZtechnik** [comment]
Confirmed fixed.

**Comment by Vogs27** [comment]
Unfortunately it doesn't work anymore... Maybe you can export the models as .step file an upload them in this repo so that they remain independent from A360 issues and changes
